object Feature {
    const val SPLASH = ":features:splash"
    const val LOGIN = ":features:login"
    const val COMPLAINT = ":features:complaint"
    const val USER_FORM = ":features:user-data"
    const val TICKET = ":features:ticket"
    const val SUGGESTION = ":features:suggestion"
    const val SIGN_UP = ":features:singup"
    const val RESET_PASSWORD = ":features:reset-password"
    const val PROFILE = ":features:profile"
    const val BOOKING = ":features:booking"
    const val EDIT_PROFILE = ":features:edit-profile"
    const val FORGET_PASSWORD = ":features:forget-password"
    const val ROUTE = ":features:route"
    const val LINE_MAP = ":features:line-map"
    const val HOME = ":features:home-screen"
    const val MAP = ":features:map"
    const val SCAN_QR = ":features:scan-qr"
}