package com.englizya.privacy_policy

object PrivacyPolicy {

    const val ENGLISH_DETAILS = "Privacy Policy\n" +
            "Last updated: May 11, 2022\n" +
            "This Privacy Policy describes Our policies and procedures on the collection,\n" +
            "use and disclosure of Your information when You use the Service and tells You\n" +
            "about Your privacy rights and how the law protects You.\n" +
            "We use Your Personal data to provide and improve the Service. By using the\n" +
            "Service, You agree to the collection and use of information in accordance with\n" +
            "this Privacy Policy. This Privacy Policy has been created with the help of the\n" +
            "[Privacy Policy Generator](https://www.termsfeed.com/privacypolicy\n" +
            "generator/).\n" +
            "Interpretation and Definitions\n" +
            "Interpretation\n" +
            "The words of which the initial letter is capitalized have meanings defined\n" +
            "under the following conditions. The following definitions shall have the same\n" +
            "meaning regardless of whether they appear in singular or in plural.\n" +

            "Definitions\n" +


            "For the purposes of this Privacy Policy:\n" +

            " \u2022 Account means a unique account created for You to access our Service or\n" +
            " parts of our Service.\n" +

            " \u2022 Affiliate means an entity that controls, is controlled by or is under\n" +
            " common control with a party, where \"control\" means ownership of 50% or\n" +
            " more of the shares, equity interest or other securities entitled to vote\n" +
            " for election of directors or other managing authority.\n" +

            " \u2022 Application means the software program provided by the Company downloaded\n" +
            " by You on any electronic device, named Englizya Bus\n" +

            " \u2022 Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this\n" +
            " Agreement) refers to Englizya, 1 Al Toukhi Street Shubra Al Balad\n" +
            " Qalyubia Egypt.\n" +

            " \u2022 Country refers to: Egypt\n" +

            " \u2022 Device means any device that can access the Service such as a computer, a\n" +
            " cellphone or a digital tablet.\n" +

            " \u2022 Personal Data is any information that relates to an identified or\n" +
            " identifiable individual.\n" +

            " \u2022 Service refers to the Application.\n" +

            " \u2022 Service Provider means any natural or legal person who processes the data\n" +
            " on behalf of the Company. It refers to third party companies or\n" +
            " individuals employed by the Company to facilitate the Service, to provide\n" +
            " the Service on behalf of the Company, to perform services related to the\n" +
            " Service or to assist the Company in analyzing how the Service is used.\n" +

            " \u2022 Usage Data refers to data collected automatically, either generated by the\n" +
            " use of the Service or from the Service infrastructure itself (for example,\n" +
            " the duration of a page visit).\n" +

            " \u2022 You means the individual accessing or using the Service, or the company,\n" +
            " or other legal entity on behalf of which such individual is accessing or\n" +
            " using the Service, as applicable.\n" +


            "Collecting and Using Your Personal Data\n" +


            "Types of Data Collected\n" +


            "Personal Data\n" +


            "While using Our Service, We may ask You to provide Us with certain personally\n" +
            "identifiable information that can be used to contact or identify You.\n" +
            "Personally identifiable information may include, but is not limited to:\n" +

            " \u2022 Email address\n" +

            " \u2022 First name and last name\n" +

            " \u2022 Phone number\n" +

            " \u2022 Address, State, Province, ZIP/Postal code, City\n" +

            " \u2022 Usage Data\n" +


            "Usage Data\n" +


            "Usage Data is collected automatically when using the Service.\n" +

            "Usage Data may include information such as Your Device\\'s Internet Protocol\n" +
            "address (e.g. IP address), browser type, browser version, the pages of our\n" +
            "Service that You visit, the time and date of Your visit, the time spent on\n" +
            "those pages, unique device identifiers and other diagnostic data.\n" +

            "When You access the Service by or through a mobile device, We may collect\n" +
            "certain information automatically, including, but not limited to, the type of\n" +
            "mobile device You use, Your mobile device unique ID, the IP address of Your\n" +
            "mobile device, Your mobile operating system, the type of mobile Internet\n" +
            "browser You use, unique device identifiers and other diagnostic data.\n" +

            "We may also collect information that Your browser sends whenever You visit our\n" +
            "Service or when You access the Service by or through a mobile device.\n" +

            "Information Collected while Using the Application\n" +


            "While using Our Application, in order to provide features of Our Application,\n" +
            "We may collect, with Your prior permission:\n" +

            " \u2022 Information regarding your location\n" +

            " \u2022 Pictures and other information from your Device\\'s camera and photo library\n" +


            "We use this information to provide features of Our Service, to improve and\n" +
            "customize Our Service. The information may be uploaded to the Company\\'s\n" +
            "servers and/or a Service Provider\\'s server or it may be simply stored on Your\n" +
            "device.\n" +

            "You can enable or disable access to this information at any time, through Your\n" +
            "Device settings.\n" +

            "Use of Your Personal Data\n" +


            "The Company may use Personal Data for the following purposes:\n" +

            " \u2022 To provide and maintain our Service , including to monitor the usage of\n" +
            " our Service.\n" +

            " \u2022 To manage Your Account: to manage Your registration as a user of the\n" +
            " Service. The Personal Data You provide can give You access to different\n" +
            " functionalities of the Service that are available to You as a registered\n" +
            " user.\n" +

            " \u2022 For the performance of a contract: the development, compliance and\n" +
            " undertaking of the purchase contract for the products, items or services\n" +
            " You have purchased or of any other contract with Us through the Service.\n" +

            " \u2022 To contact You: To contact You by email, telephone calls, SMS, or other\n" +
            " equivalent forms of electronic communication, such as a mobile\n" +
            " application\\'s push notifications regarding updates or informative\n" +
            " communications related to the functionalities, products or contracted\n" +
            " services, including the security updates, when necessary or reasonable for\n" +
            " their implementation.\n" +

            " \u2022 To provide You with news, special offers and general information about\n" +
            " other goods, services and events which we offer that are similar to those\n" +
            " that you have already purchased or enquired about unless You have opted\n" +
            " not to receive such information.\n" +

            " \u2022 To manage Your requests: To attend and manage Your requests to Us.\n" +

            " \u2022 For business transfers: We may use Your information to evaluate or conduct\n" +
            " a merger, divestiture, restructuring, reorganization, dissolution, or\n" +
            " other sale or transfer of some or all of Our assets, whether as a going\n" +
            " concern or as part of bankruptcy, liquidation, or similar proceeding, in\n" +
            " which Personal Data held by Us about our Service users is among the assets\n" +
            " transferred.\n" +

            " \u2022 For other purposes : We may use Your information for other purposes, such\n" +
            " as data analysis, identifying usage trends, determining the effectiveness\n" +
            " of our promotional campaigns and to evaluate and improve our Service,\n" +
            " products, services, marketing and your experience.\n" +


            "We may share Your personal information in the following situations:\n" +

            " \u2022 With Service Providers: We may share Your personal information with\n" +
            " Service Providers to monitor and analyze the use of our Service, to\n" +
            " contact You.\n" +
            " \u2022 For business transfers: We may share or transfer Your personal information\n" +
            " in connection with, or during negotiations of, any merger, sale of Company\n" +
            " assets, financing, or acquisition of all or a portion of Our business to\n" +
            " another company.\n" +
            " \u2022 With Affiliates: We may share Your information with Our affiliates, in\n" +
            " which case we will require those affiliates to honor this Privacy Policy.\n" +
            " Affiliates include Our parent company and any other subsidiaries, joint\n" +
            " venture partners or other companies that We control or that are under\n" +
            " common control with Us.\n" +
            " \u2022 With business partners: We may share Your information with Our business\n" +
            " partners to offer You certain products, services or promotions.\n" +
            " \u2022 With other users: when You share personal information or otherwise\n" +
            " interact in the public areas with other users, such information may be\n" +
            " viewed by all users and may be publicly distributed outside.\n" +
            " \u2022 With Your consent : We may disclose Your personal information for any\n" +
            " other purpose with Your consent.\n" +

            "Retention of Your Personal Data\n" +


            "The Company will retain Your Personal Data only for as long as is necessary\n" +
            "for the purposes set out in this Privacy Policy. We will retain and use Your\n" +
            "Personal Data to the extent necessary to comply with our legal obligations\n" +
            "(for example, if we are required to retain your data to comply with applicable\n" +
            "laws), resolve disputes, and enforce our legal agreements and policies.\n" +

            "The Company will also retain Usage Data for internal analysis purposes. Usage\n" +
            "Data is generally retained for a shorter period of time, except when this data\n" +
            "is used to strengthen the security or to improve the functionality of Our\n" +
            "Service, or We are legally obligated to retain this data for longer time\n" +
            "periods.\n" +

            "Transfer of Your Personal Data\n" +


            "Your information, including Personal Data, is processed at the Company's\n" +
            "operating offices and in any other places where the parties involved in the\n" +
            "processing are located. It means that this information may be transferred to —\n" +
            "and maintained on — computers located outside of Your state, province, country\n" +
            "or other governmental jurisdiction where the data protection laws may differ\n" +
            "than those from Your jurisdiction.\n" +

            "Your consent to this Privacy Policy followed by Your submission of such\n" +
            "information represents Your agreement to that transfer.\n" +

            "The Company will take all steps reasonably necessary to ensure that Your data\n" +
            "is treated securely and in accordance with this Privacy Policy and no transfer\n" +
            "of Your Personal Data will take place to an organization or a country unless\n" +
            "there are adequate controls in place including the security of Your data and\n" +
            "other personal information.\n" +

            "Disclosure of Your Personal Data\n" +


            "Business Transactions\n" +


            "If the Company is involved in a merger, acquisition or asset sale, Your\n" +
            "Personal Data may be transferred. We will provide notice before Your Personal\n" +
            "Data is transferred and becomes subject to a different Privacy Policy.\n" +

            "Law enforcement\n" +


            "Under certain circumstances, the Company may be required to disclose Your\n" +
            "Personal Data if required to do so by law or in response to valid requests by\n" +
            "public authorities (e.g. a court or a government agency).\n" +

            "Other legal requirements\n" +


            "The Company may disclose Your Personal Data in the good faith belief that such\n" +
            "action is necessary to:\n" +

            " \u2022 Comply with a legal obligation\n" +
            " \u2022 Protect and defend the rights or property of the Company\n" +
            " \u2022 Prevent or investigate possible wrongdoing in connection with the Service\n" +
            " \u2022 Protect the personal safety of Users of the Service or the public\n" +
            " \u2022 Protect against legal liability\n" +

            "Security of Your Personal Data\n" +


            "The security of Your Personal Data is important to Us, but remember that no\n" +
            "method of transmission over the Internet, or method of electronic storage is\n" +
            "100% secure. While We strive to use commercially acceptable means to protect\n" +
            "Your Personal Data, We cannot guarantee its absolute security.\n" +

            "Detailed Information on the Processing of Your Personal Data\n" +


            "The Service Providers We use may have access to Your Personal Data. These\n" +
            "third party vendors collect, store, use, process and transfer information\n" +
            "about Your activity on Our Service in accordance with their Privacy Policies.\n" +

            "Usage, Performance and Miscellaneous\n" +


            "We may use third party Service Providers to provide better improvement of our\n" +
            "Service.\n" +

            " \u2022 Google Places\n" +

            " Google Places is a service that returns information about places using\n" +
            " HTTP requests. It is operated by Google\n" +

            " Google Places service may collect information from You and from Your\n" +
            " Device for security purposes.\n" +

            " The information gathered by Google Places is held in accordance with the\n" +
            " Privacy Policy of Google:\n" +
            " Children's Privacy\n" +


            "Our Service does not address anyone under the age of 13. We do not knowingly\n" +
            "collect personally identifiable information from anyone under the age of 13.\n" +
            "If You are a parent or guardian and You are aware that Your child has provided\n" +
            "Us with Personal Data, please contact Us. If We become aware that We have\n" +
            "collected Personal Data from anyone under the age of 13 without verification\n" +
            "of parental consent, We take steps to remove that information from Our\n" +
            "servers.\n" +

            "If We need to rely on consent as a legal basis for processing Your information\n" +
            "and Your country requires consent from a parent, We may require Your parent's\n" +
            "consent before We collect and use that information.\n" +

            "Links to Other Websites\n" +


            "Our Service may contain links to other websites that are not operated by us.\n" +
            "If you click on a third party link, You will be directed to that third party's\n" +
            "Site. We strongly advise you to review the Privacy Policy of every site you\n" +
            "Visit.\n" +

            "We have no control over and assume no responsibility for the content, privacy\n" +
            "Policies or practices of any third party sites or services.\n" +

            "Changes to this Privacy Policy\n" +


            "We may update Our Privacy Policy from time to time. We will notify You of any\n" +
            "Changes by posting the new Privacy Policy on this page.\n" +

            "We will let You know via email and/or a prominent notice on Our Service, prior\n" +
            "to the change becoming effective and update the \"Last updated\" date at the top\n" +
            "of this Privacy Policy.\n" +

            "You are advised to review this Privacy Policy periodically for any changes.\n" +
            "Changes to this Privacy Policy are effective when they are posted on this\n" +
            "page.\n" +
            "Contact Us\n" +
            "If you have any questions about this Privacy Policy, You can contact us:\n" +
            " \u2022 By email: info@englizya.com\n" +
            " \u2022 By visiting this page on our website: englizya.com\n" +
            " \u2022 By phone number: +20 122 451 8411\n" +
            "\n"

    const val ARABIC_DETAILS =
        " سياسة الخصوصية\n" +
                "آخر تحديث: 11 مايو 2022\n" +
                "تصف سياسة الخصوصية هذه سياساتنا وإجراءاتنا بشأن المجموعة ،\n" +
                "استخدام والكشف عن معلوماتك عند استخدام الخدمة وإخبارك\n" +
                "حول حقوق الخصوصية الخاصة بك وكيف يحميك القانون.\n" +
                "نستخدم بياناتك الشخصية لتوفير الخدمة وتحسينها. باستخدام ملف\n" +
                "الخدمة ، أنت توافق على جمع واستخدام المعلومات وفقًا لـ\n" +
                "سياسة الخصوصية .\n" +
                "التفسير والتعريفات\n" +
                "تفسير\n" +
                "الكلمات التي يتم كتابة الحرف الأول بها معاني محددة\n" +
                "ظل الظروف التالية. يجب أن يكون للتعريفات التالية نفس التعريف\n" +
                "المعنى بغض النظر عما إذا كانت تظهر بصيغة المفرد أو الجمع.\n" +
                "تعريفات\n" +
                "لأغراض سياسة الخصوصية هذه:\n" +
                "\u2022 الحساب يعني حسابًا فريدًا تم إنشاؤه لك للوصول إلى خدمتنا أو\n" +
                "أجزاء من خدمتنا.\n" +
                "\u2022 الشركة التابعة تعني الكيان الذي يتحكم أو يتحكم فيه أو يخضع له\n" +
                "السيطرة المشتركة مع حزب ، حيث تعني \"السيطرة\" ملكية 50٪ أو\n" +
                "المزيد من الأسهم أو حقوق الملكية أو الأوراق المالية الأخرى التي يحق لها التصويت\n" +
                "لانتخاب أعضاء مجلس الإدارة أو أي سلطة إدارية أخرى.\n" +
                "\u2022 التطبيق يعني البرنامج الذي توفره الشركة الذي تم تنزيله\n" +
                "بواسطتك على أي جهاز إلكتروني يسمى Englizya Bus\n" +
                "\u2022 الشركة (يشار إليها باسم \"الشركة\" أو \"نحن\" أو \"نحن\" أو \"لدينا\" في هذا\n" +
                "الاتفاقية) تشير إلى اللغة الإنجليزية ، 1 الطوخي شارع شبرا البلد\n" +
                "القليوبية مصر .\n" +
                "\u2022 الدولة تشير إلى: مصر\n" +

                "\u2022 الجهاز يعني أي جهاز يمكنه الوصول إلى الخدمة مثل الكمبيوتر ، أ\n" +
                "الهاتف المحمول أو الكمبيوتر اللوحي الرقمي.\n" +

                "\u2022 البيانات الشخصية هي أي معلومات تتعلق بملف أو\n" +
                "فرد يمكن التعرف عليه .\n" +

                "\u2022 تشير الخدمة إلى التطبيق.\n" +

                "\u2022 مقدم الخدمة يعني أي شخص طبيعي أو اعتباري يقوم بمعالجة البيانات\n" +
                "نيابة عن الشركة. يشير إلى شركات الطرف الثالث أو\n" +
                "الأفراد الذين توظفهم الشركة لتسهيل تقديم الخدمة\n" +
                "الخدمة نيابة عن الشركة ، لأداء الخدمات المتعلقة بـ\n" +
                "الخدمة أو لمساعدة الشركة في تحليل كيفية استخدام الخدمة.\n" +

                "\u2022 تشير بيانات الاستخدام إلى البيانات التي يتم جمعها تلقائيًا ، سواء تم إنشاؤها بواسطة\n" +
                "استخدام الخدمة أو من البنية التحتية للخدمة نفسها (على سبيل المثال ،\n" +
                "مدة زيارة الصفحة).\n" +

                "\u2022 أنت تعني الفرد الذي يصل إلى الخدمة أو يستخدمها ، أو الشركة ،\n" +
                "أو أي كيان قانوني آخر يقوم هذا الفرد بالوصول نيابة عنه أو\n" +
                "استخدام الخدمة ، حسب الاقتضاء.\n" +


                "جمع واستخدام بياناتك الشخصية\n" +


                "أنواع البيانات المجمعة\n" +


                "بيانات شخصية\n" +


                "أثناء استخدام خدمتنا ، قد نطلب منك تزويدنا ببعض الأمور بشكل شخصي\n" +
                "التعريف التي يمكن استخدامها للاتصال أو التعرف عليك.\n" +
                "قد تتضمن معلومات التعريف الشخصية ، على سبيل المثال لا الحصر:\n" +

                "\u2022 عنوان بريد الكتروني\n" +

                "\u2022 الاسم الأول واسم العائلة\n" +

                "\u2022 رقم الهاتف\n" +

                "\u2022 العنوان ، الولاية ، المقاطعة ، الرمز البريدي / الرمز البريدي ، المدينة\n" +

                "\u2022 بيانات الاستخدام\n" +


                "بيانات الاستخدام\n" +


                "يتم جمع بيانات الاستخدام تلقائيًا عند استخدام الخدمة.\n" +

                "قد تتضمن بيانات الاستخدام معلومات مثل بروتوكول الإنترنت الخاص بجهازك\n" +
                "العنوان (مثل عنوان IP) ، ونوع المتصفح ، وإصدار المتصفح ، وصفحات\n" +
                "الخدمة التي تزورها ، وقت وتاريخ زيارتك ، الوقت الذي تقضيه\n" +
                "تلك الصفحات ومعرفات الجهاز الفريدة وبيانات التشخيص الأخرى.\n" +

                "عندما تصل إلى الخدمة عن طريق أو من خلال جهاز محمول ، يجوز لنا جمع\n" +
                "معينة تلقائيًا ، بما في ذلك ، على سبيل المثال لا الحصر ، نوع\n" +
                "المحمول الذي تستخدمه ، المعرف الفريد لجهازك المحمول ، وعنوان IP الخاص بك\n" +
                "محمول ، نظام تشغيل هاتفك المحمول ، نوع الإنترنت عبر الهاتف المحمول\n" +
                "المتصفح الذي تستخدمه ومعرّفات الجهاز الفريدة وبيانات التشخيص الأخرى.\n" +

                "قد نقوم أيضًا بجمع المعلومات التي يرسلها متصفحك عندما تزور موقعنا\n" +
                "الخدمة أو عند الوصول إلى الخدمة عن طريق أو من خلال جهاز محمول.\n" +

                "المعلومات التي تم جمعها أثناء استخدام التطبيق\n" +


                "أثناء استخدام تطبيقنا ، من أجل توفير ميزات تطبيقنا ،\n" +
                "قد نجمع ، بإذن مسبق منك :\n" +

                "\u2022 معلومات بخصوص موقعك\n" +

                "\u2022 الصور والمعلومات الأخرى من كاميرا جهازك ومكتبة الصور\n" +


                "نستخدم هذه المعلومات لتوفير ميزات خدمتنا لتحسين و\n" +
                "تخصيص خدمتنا. قد يتم تحميل المعلومات إلى الشركة\n" +
                "الخوادم و / أو خادم مزود الخدمة أو قد يتم تخزينها ببساطة على\n" +
                "الجهاز .\n" +

                "يمكنك تمكين أو تعطيل الوصول إلى هذه المعلومات في أي وقت ، من خلال Your\n" +
                "إعدادات الجهاز.\n" +

                "استخدام بياناتك الشخصية\n" +


                "يجوز للشركة استخدام البيانات الشخصية للأغراض التالية:\n" +

                "\u2022 لتقديم خدماتنا وصيانتها ، بما في ذلك مراقبة استخدام\n" +
                "خدمتنا .\n" +

                "\u2022 لإدارة حسابك : لإدارة تسجيلك كمستخدم في\n" +
                "خدمة. يمكن أن تمنحك البيانات الشخصية التي تقدمها وصولاً إلى بيانات مختلفة\n" +
                "وظائف الخدمة المتاحة لك كمسجل\n" +
                "مستخدم .\n" +

                "\u2022 لأداء العقد: التطوير والامتثال و\n" +
                "تعهد بعقد شراء المنتجات أو الأصناف أو الخدمات\n" +
                "لقد اشتريت أو أي عقد آخر معنا من خلال الخدمة.\n" +

                "\u2022 للاتصال بك : للاتصال بك عن طريق البريد الإلكتروني أو المكالمات الهاتفية أو الرسائل القصيرة أو غيرها\n" +
                "أشكال مكافئة من الاتصالات الإلكترونية ، مثل الهاتف المحمول\n" +
                "إخطارات التطبيق فيما يتعلق بالتحديثات أو بالمعلومات\n" +
                "الاتصالات المتعلقة بالوظائف أو المنتجات أو المتعاقد عليها\n" +
                "الخدمات ، بما في ذلك التحديثات الأمنية ، عند الضرورة أو معقولة ل\n" +
                "تنفيذها .\n" +

                "\u2022 لتزويدك بالأخبار والعروض الخاصة والمعلومات العامة حول\n" +
                "السلع والخدمات والأحداث الأخرى التي نقدمها مماثلة لتلك\n" +
                "التي اشتريتها بالفعل أو استفسرت عنها ما لم تكن قد اخترت\n" +
                "عدم تلقي مثل هذه المعلومات.\n" +

                "\u2022 لإدارة طلباتك : لحضور وإدارة طلباتك إلينا.\n" +

                "\u2022 بالنسبة لعمليات نقل الأعمال: قد نستخدم معلوماتك للتقييم أو السلوك\n" +
                "الاندماج أو التجريد أو إعادة الهيكلة أو إعادة التنظيم أو الحل أو\n" +
                "عمليات بيع أو نقل أخرى لبعض أو كل أصولنا ، سواء أكان ذلك مستمرًا\n" +
                "قلق أو كجزء من إفلاس أو تصفية أو إجراء مشابه ، في\n" +
                "البيانات الشخصية التي نحتفظ بها عن مستخدمي خدمتنا هي من بين الأصول\n" +
                "نقل .\n" +

                "\u2022 لأغراض أخرى: قد نستخدم معلوماتك لأغراض أخرى ، مثل\n" +
                "كتحليل البيانات ، وتحديد اتجاهات الاستخدام ، وتحديد الفعالية\n" +
                "لحملاتنا الترويجية ولتقييم وتحسين خدماتنا ،\n" +
                "المنتجات والخدمات والتسويق وتجربتك.\n" +


                "قد نشارك معلوماتك الشخصية في المواقف التالية:\n" +

                "\u2022 مع مزودي الخدمة: قد نشارك معلوماتك الشخصية مع\n" +
                "يقوم مقدمو الخدمة بمراقبة وتحليل استخدام خدمتنا إلى\n" +
                "اتصل بك.\n" +
                "معلوماتك الشخصية أو نقلها\n" +
                "فيما يتعلق ، أو أثناء المفاوضات ، بشأن أي عملية بيع اندماج للشركة\n" +
                "الأصول أو التمويل أو الاستحواذ على كل أو جزء من أعمالنا\n" +
                "شركة أخرى .\n" +
                "\u2022 مع الشركات التابعة: قد نشارك معلوماتك مع الشركات التابعة لنا ، في\n" +
                "في هذه الحالة سنطلب من تلك الشركات التابعة احترام سياسة الخصوصية هذه.\n" +
                "تشمل الشركات التابعة شركتنا الأم وأي شركات فرعية أخرى ، مشتركة\n" +
                "شركاء المشروع أو الشركات الأخرى التي نتحكم فيها أو التي تخضع لها\n" +
                "السيطرة المشتركة معنا.\n" +
                "\u2022 مع شركاء الأعمال: قد نشارك معلوماتك مع أعمالنا\n" +
                "شركاء ليقدموا لك منتجات أو خدمات أو عروض ترويجية معينة.\n" +
                "\u2022 مع مستخدمين آخرين: عند مشاركة معلومات شخصية أو غير ذلك\n" +
                "تتفاعل في الأماكن العامة مع مستخدمين آخرين ، قد تكون هذه المعلومات\n" +
                "تمت مشاهدتها من قبل جميع المستخدمين ويمكن توزيعها علنًا في الخارج.\n" +
                "\u2022 بموافقتك: يجوز لنا الكشف عن معلوماتك الشخصية لأي\n" +
                "غرض آخر بموافقتك.\n" +

                "الاحتفاظ ببياناتك الشخصية\n" +


                "ستحتفظ الشركة ببياناتك الشخصية فقط طالما كان ذلك ضروريًا\n" +
                "للأغراض المنصوص عليها في سياسة الخصوصية هذه. سوف نحتفظ بك ونستخدم ملفات\n" +
                "البيانات الشخصية بالقدر اللازم للامتثال لالتزاماتنا القانونية\n" +
                "( على سبيل المثال ، إذا طُلب منا الاحتفاظ ببياناتك للامتثال لما هو معمول به\n" +
                "القوانين ) وحل النزاعات وفرض اتفاقياتنا وسياساتنا القانونية.\n" +

                "ستحتفظ الشركة أيضًا ببيانات الاستخدام لأغراض التحليل الداخلي. إستعمال\n" +
                "يتم الاحتفاظ بالبيانات عمومًا لفترة زمنية أقصر ، باستثناء هذه البيانات\n" +
                "يستخدم لتعزيز الأمن أو لتحسين وظائف\n" +
                "الخدمة ، أو نحن ملزمون قانونًا بالاحتفاظ بهذه البيانات لفترة أطول\n" +
                "فترات .\n" +

                "نقل بياناتك الشخصية\n" +


                "تتم معالجة معلوماتك ، بما في ذلك البيانات الشخصية ، في الشركة\n" +
                "التشغيل وفي أي أماكن أخرى يكون فيها الأطراف المشاركة في\n" +
                "تقع المعالجة . هذا يعني أنه يمكن نقل هذه المعلومات إلى -\n" +
                "وتتم صيانتها على أجهزة كمبيوتر موجودة خارج ولايتك أو مقاطعتك أو بلدك\n" +
                "أو أي سلطة قضائية حكومية أخرى قد تختلف فيها قوانين حماية البيانات\n" +
                "من تلك الموجودة في ولايتك القضائية.\n" +

                "موافقتك على سياسة الخصوصية هذه متبوعة بتقديمك لهذا\n" +
                "المعلومات موافقتك على هذا النقل.\n" +

                "ستتخذ الشركة جميع الخطوات اللازمة بشكل معقول لضمان بياناتك\n" +
                "يتم التعامل معها بشكل آمن ووفقًا لسياسة الخصوصية هذه وعدم النقل\n" +
                "من بياناتك الشخصية إلى منظمة أو دولة ما لم\n" +
                "هناك ضوابط كافية مطبقة بما في ذلك أمان بياناتك و\n" +
                "معلومات شخصية أخرى .\n" +

                "الإفصاح عن بياناتك الشخصية\n" +


                "المعاملات التجارية\n" +


                "إذا كانت الشركة متورطة في عملية اندماج أو استحواذ أو بيع أصول ، فسيكون لديك\n" +
                "قد يتم نقل البيانات الشخصية. سنقدم إشعارًا قبل حسابك الشخصي\n" +
                "يتم نقل البيانات وتخضع لسياسة خصوصية مختلفة.\n" +

                "تطبيق القانون\n" +


                "في ظل ظروف معينة ، قد يُطلب من الشركة الكشف عن\n" +
                "البيانات الشخصية إذا كان ذلك مطلوبًا بموجب القانون أو استجابة لطلبات صالحة من قبل\n" +
                "العامة (مثل محكمة أو وكالة حكومية).\n" +

                "المتطلبات القانونية الأخرى\n" +


                "قد تفصح الشركة عن بياناتك الشخصية بحسن نية\n" +
                "الإجراء ضروري من أجل:\n" +

                "\u2022 الامتثال لالتزام قانوني\n" +
                "\u2022 حماية والدفاع عن حقوق أو ممتلكات الشركة\n" +
                "\u2022 منع أو التحقيق في أي مخالفات محتملة تتعلق بالخدمة\n" +
                "\u2022 حماية السلامة الشخصية لمستخدمي الخدمة أو الجمهور\n" +
                "\u2022 الحماية من المسؤولية القانونية\n" +

                "أمن بياناتك الشخصية\n" +


                "يُعد أمان بياناتك الشخصية أمرًا مهمًا بالنسبة لنا ، ولكن تذكر أنه لا\n" +
                "طريقة الإرسال عبر الإنترنت ، أو طريقة التخزين الإلكترونية\n" +
                "100٪ آمن. بينما نسعى جاهدين لاستخدام وسائل مقبولة تجاريًا للحماية\n" +
                "بياناتك الشخصية ، لا يمكننا ضمان أمنها المطلق.\n" +

                "معلومات مفصلة عن معالجة بياناتك الشخصية\n" +


                "قد يتمكن مقدمو الخدمة الذين نستخدمهم من الوصول إلى بياناتك الشخصية. هؤلاء\n" +
                "الطرف الثالث بجمع المعلومات وتخزينها واستخدامها ومعالجتها ونقلها\n" +
                "حول نشاطك على خدمتنا وفقًا لسياسات الخصوصية الخاصة بهم.\n" +

                "الاستخدام والأداء ومتنوعة\n" +


                "قد نستخدم مزودي خدمة من أطراف ثالثة لتقديم تحسين أفضل لدينا\n" +
                "خدمة.\n" +

                "\u2022 أماكن Google\n" +

                "أماكن Google هي خدمة تعرض معلومات حول الأماكن التي تستخدم\n" +
                "طلبات HTTP. يتم تشغيله من قبل جوجل\n" +

                "قد تقوم خدمة أماكن Google بجمع معلومات منك ومن حسابك\n" +
                "جهاز لأغراض أمنية.\n" +

                "يتم الاحتفاظ بالمعلومات التي تم جمعها بواسطة أماكن Google وفقًا لـ\n" +
                "سياسة الخصوصية الخاصة بـ Google:\n" +

                "خصوصية الأطفال\n" +


                "خدمتنا لا تخاطب أي شخص دون سن 13 عامًا. نحن لا نعلم ذلك عن قصد\n" +
                "جمع معلومات التعريف الشخصية من أي شخص يقل عمره عن 13 عامًا.\n" +
                "إذا كنت أحد الوالدين أو الوصي وكنت على علم بأن طفلك قد قدم\n" +
                "لنا مع البيانات الشخصية ، يرجى الاتصال بنا . إذا علمنا أن لدينا\n" +
                "تم جمع البيانات الشخصية من أي شخص يقل عمره عن 13 عامًا دون التحقق\n" +
                "موافقة الوالدين ، نتخذ خطوات لإزالة تلك المعلومات من موقعنا\n" +
                "الخوادم .\n" +

                "إذا احتجنا إلى الاعتماد على الموافقة كأساس قانوني لمعالجة معلوماتك\n" +
                "، وقد نطلب موافقة والديك\n" +
                "الموافقة قبل أن نجمع هذه المعلومات ونستخدمها.\n" +

                "روابط لمواقع أخرى\n" +


                "قد تحتوي خدمتنا على روابط لمواقع أخرى لا نقوم بتشغيلها .\n" +
                "قمت بالنقر فوق ارتباط جهة خارجية ، فسيتم توجيهك إلى هذا الطرف الثالث\n" +
                "موقع. ننصحك بشدة بمراجعة سياسة الخصوصية لكل موقع تقوم به\n" +
                "زيارة.\n" +

                "ليس لدينا أي سيطرة ولا نتحمل أي مسؤولية عن المحتوى والخصوصية\n" +
                "سياسات أو ممارسات أي مواقع أو خدمات خاصة بطرف ثالث.\n" +

                "التغييرات على سياسة الخصوصية هذه\n" +


                "قد نقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. سوف نخطرك بأي\n" +
                "التغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة.\n" +

                "سنخبرك عبر البريد الإلكتروني و / أو إشعارًا بارزًا على خدمتنا مسبقًا\n" +
                "ليصبح التغيير ساريًا وتحديث تاريخ \"آخر تحديث\" في الأعلى\n" +
                "من سياسة الخصوصية هذه.\n" +

                "يُنصح بمراجعة سياسة الخصوصية هذه بشكل دوري لمعرفة أي تغييرات.\n" +
                "تسري التغييرات التي تطرأ على سياسة الخصوصية هذه عند نشرها في هذا الشأن\n" +
                "الصفحة .\n" +
                "اتصل بنا\n" +
                "إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه ، يمكنك الاتصال بنا:\n" +
                "\u2022 عن طريق البريد الإلكتروني: info@englizya.com\n" +
                "\u2022 من خلال زيارة هذه الصفحة على موقعنا: \n" +
                "\u2022 عن طريق رقم الهاتف: +20122451 8411\n"
}