package com.englizya.common.utils.navigation

object Destination {
    const val AboutUs = "about-us"
    const val ContactUs = "contact-us"
    const val TERMS_AND_CONDITIONS = "terms-and-conditions"
    const val USER_TICKETS = "user-tickets"
    const val PAYMENT_HISTORY = "payment-history"
    const val PROFILE = "profile"
    const val SUGGEST_IDEA = "suggest-idea"
    const val COMPLAINT = "insert-complaint"
    const val DRIVER_REVIEW = "review-driver"
    const val SETTINGS =  "settings"
    const val PAYMENT: String = "booking-payment"
    const val SELECT_SEAT = "select-seat"
    const val SELECT_TRIP = "select-trip"
    const val SELECT_STATION = "select-station"
    const val HOME: String = "home"
    const val SET_PASSWORD: String = "set-password"
    const val RESET_PASSWORD = "reset-password"
    const val USER_FORM = "user-form"
    const val SPLASH = "splash"
    const val LOGIN: String = "login"
    const val TICKET = "ticket"
    const val SEND_OTP = "send-otp"
    const val PRIVACY_POLICY = "privacy-policy"
    const val RECHARGING = "recharging"
    const val REFUND_POLICY = "refund-policy"
}